/* ═══════════════════════════════════════════════════════════════════
   MEDBORGARSKAPSPROVET — preparación para el examen de ciudadanía sueca
   Sección INDEPENDIENTE: su propio progreso (tabla medborgarskap_progress),
   no afecta el progreso general de Aprender.
   ═══════════════════════════════════════════════════════════════════ */

const MEDBORGAR = {
  modules: [
    {
      id: "m01", title: "Sverige som land", active: true,
      aprende: "Suecia (**Sverige**) es un país nórdico del norte de Europa. Su capital (**huvudstad**) es **Stockholm** y su moneda es la corona sueca (**krona**). El idioma principal es el sueco (**svenska**). Suecia es una monarquía constitucional: el jefe de Estado (**statschef**) es el rey (**kung**), pero tiene una función simbólica y no gobierna. El poder político lo tienen el parlamento (**Riksdag**) y el gobierno (**regering**). El país se divide en municipios (**kommun**) y regiones. Los habitantes (**invånare**) pagan impuestos (**skatt**) que financian la sanidad, la escuela y el bienestar. La economía se apoya en recursos naturales (**naturresurser**) como el bosque (**skog**), el hierro (**järnmalm**) y la energía hidráulica (**vattenkraft**).",
      palabras: [{"sv":"Sverige","es":"Suecia"},{"sv":"huvudstad","es":"capital"},{"sv":"kung","es":"rey"},{"sv":"statschef","es":"jefe de Estado"},{"sv":"Riksdag","es":"parlamento"},{"sv":"regering","es":"gobierno"},{"sv":"kommun","es":"municipio"},{"sv":"skatt","es":"impuesto"},{"sv":"skog","es":"bosque"},{"sv":"järnmalm","es":"mineral de hierro"}],
      questions: [
        {"q":"Vem är Sveriges statschef?","qEs":"¿Quién es el jefe de Estado de Suecia?","options":["Presidenten","Kungen","Statsministern","Riksdagen"],"correct":1,"exp":"El jefe de Estado de Suecia es el rey; tiene una función simbólica.","phrase":"Rätt! Sveriges statschef är kungen.","why":"Suecia es una monarquía constitucional: el rey es el jefe de Estado pero no gobierna. Las decisiones políticas las toman el Riksdag (parlamento) y el gobierno."},
        {"q":"Vad heter Sveriges huvudstad?","qEs":"¿Cuál es la capital de Suecia?","options":["Stockholm","Uppsala","Göteborg","Malmö"],"correct":0,"exp":"La capital de Suecia es Estocolmo.","phrase":"Rätt! Sveriges huvudstad är Stockholm.","why":"Estocolmo es la ciudad más grande y la capital, donde se encuentran el Riksdag y el gobierno."},
        {"q":"Vilken naturresurs är viktig för Sveriges ekonomi?","qEs":"¿Qué recurso natural es importante para la economía de Suecia?","options":["Olja","Skog","Guld","Diamanter"],"correct":1,"exp":"El bosque (madera) es un recurso natural clave para la economía sueca, junto con el hierro y la energía hidráulica.","phrase":"Rätt! Skogen är en viktig naturresurs i Sverige.","why":"Suecia tiene enormes bosques; la industria de la madera y el papel es histórica. También son importantes el hierro (järnmalm) y la energía hidroeléctrica (vattenkraft). Suecia no es un país petrolero."},
        {"q":"Vilket är Sveriges officiella huvudspråk?","qEs":"¿Cuál es el idioma oficial principal de Suecia?","options":["Danska","Finska","Svenska","Norska"],"correct":2,"exp":"El idioma principal oficial de Suecia es el sueco.","phrase":"Rätt! Sveriges huvudspråk är svenska.","why":"El sueco es el idioma principal. Además hay cinco lenguas minoritarias reconocidas (como el finés y el sami)."},
        {"q":"Vad heter Sveriges valuta?","qEs":"¿Cómo se llama la moneda de Suecia?","options":["Krona","Pund","Dollar","Euro"],"correct":0,"exp":"La moneda de Suecia es la corona sueca (krona).","phrase":"Rätt! Sveriges valuta är svenska kronor.","why":"Aunque Suecia es miembro de la Unión Europea, no usa el euro; mantiene su propia moneda, la corona (krona)."},
        {"q":"En person vill veta vem som styr Sverige politiskt. Vad är rätt?","qEs":"Una persona quiere saber quién gobierna Suecia políticamente. ¿Qué es correcto?","options":["Riksdagen och regeringen","Kungen ensam","Domstolarna","Företagen"],"correct":0,"isCase":true,"exp":"El poder político lo tienen el Riksdag (parlamento) y el gobierno, no el rey.","phrase":"Rätt! Riksdagen och regeringen styr Sverige politiskt.","why":"El rey es un jefe de Estado simbólico. Quienes aprueban las leyes y gobiernan el país son el Riksdag (elegido por el pueblo) y el gobierno (regering), que responde ante el Riksdag."},
        {"q":"Vilken färg har den svenska flaggan?","qEs":"¿De qué color es la bandera sueca?","options":["Vit med blått kors","Grön med gult kors","Blå med gult kors","Röd med vitt kors"],"correct":2,"exp":"La bandera sueca es azul con una cruz amarilla.","phrase":"Rätt! Flaggan är blå med gult kors."},
        {"q":"Ungefär hur många invånare har Sverige?","qEs":"¿Aproximadamente cuántos habitantes tiene Suecia?","options":["Cirka 10 miljoner","Cirka 100 miljoner","Cirka 2 miljoner","Cirka 50 miljoner"],"correct":0,"exp":"Suecia tiene alrededor de 10 millones de habitantes.","phrase":"Rätt! Sverige har cirka 10 miljoner invånare."},
        {"q":"Vilket land gränsar till Sverige i väster?","qEs":"¿Qué país limita con Suecia al oeste?","options":["Tyskland","Danmark","Norge","Ryssland"],"correct":2,"exp":"Noruega está al oeste; Finlandia al noreste.","phrase":"Rätt! Norge ligger väster om Sverige."},
        {"q":"Hur är klimatet i norra Sverige på vintern?","qEs":"¿Cómo es el clima en el norte de Suecia en invierno?","options":["Varmt och tropiskt","Alltid soligt","Kallt med mycket snö","Torrt som en öken"],"correct":2,"exp":"El norte de Suecia es frío y con mucha nieve en invierno.","phrase":"Rätt! I norr är vintern kall och snörik."}
      ]
    },
    {
      id: "m02", title: "Demokrati", active: true,
      aprende: "Democracia (**demokrati**) significa que el pueblo (**folket**) decide. En Suecia, todos los que tienen al menos 18 años pueden votar (**rösta**) en elecciones libres. Las bases de la democracia son: elecciones libres, igualdad de todos ante la ley, libertad de expresión (**yttrandefrihet**) y varios partidos (pluralismo). Suecia es una democracia desde principios del siglo XX; el sufragio universal (**allmän rösträtt**) para hombres y mujeres llegó en 1921. Las decisiones se toman por mayoría (**majoritet**), pero también se protegen los derechos de las minorías y los derechos humanos (**mänskliga rättigheter**).",
      palabras: [{"sv":"demokrati","es":"democracia"},{"sv":"folket","es":"el pueblo"},{"sv":"rösta","es":"votar"},{"sv":"yttrandefrihet","es":"libertad de expresión"},{"sv":"allmän rösträtt","es":"sufragio universal"},{"sv":"majoritet","es":"mayoría"}],
      questions: [
        {"q":"Vad betyder demokrati?","qEs":"¿Qué significa democracia?","options":["Kungen bestämmer","Militären bestämmer","Folket bestämmer","En person bestämmer"],"correct":2,"exp":"Democracia significa que el pueblo decide.","phrase":"Rätt! I en demokrati bestämmer folket.","why":"En una democracia el poder viene del pueblo, que elige a sus representantes en elecciones libres."},
        {"q":"Från vilken ålder får man rösta i Sverige?","qEs":"¿A partir de qué edad se puede votar en Suecia?","options":["15 år","18 år","21 år","16 år"],"correct":1,"exp":"Se puede votar a partir de los 18 años.","phrase":"Rätt! Man får rösta från 18 års ålder."},
        {"q":"Vilket är ett kännetecken för en demokrati?","qEs":"¿Cuál es un rasgo de una democracia?","options":["Fria val","Ingen yttrandefrihet","Bara ett parti","Kungen styr ensam"],"correct":0,"exp":"Las elecciones libres son un rasgo de la democracia.","phrase":"Rätt! Fria val är viktigt i en demokrati.","why":"Las elecciones libres, la igualdad ante la ley y la libertad de expresión son pilares de la democracia."},
        {"q":"När fick kvinnor rösträtt i Sverige?","qEs":"¿Cuándo obtuvieron las mujeres el derecho al voto en Suecia?","options":["1850","1975","1921","2000"],"correct":2,"exp":"Las mujeres obtuvieron el derecho al voto en 1921.","phrase":"Rätt! Kvinnor fick rösträtt 1921.","why":"El sufragio universal (allmän rösträtt) para hombres y mujeres se implementó en 1921, un hito de la democracia sueca."},
        {"q":"En medborgare vill påverka samhället. Vad kan hen göra i en demokrati?","qEs":"Un ciudadano quiere influir en la sociedad. ¿Qué puede hacer en una democracia?","options":["Flytta utomlands","Ingenting","Rösta i valet","Betala mer skatt"],"correct":2,"isCase":true,"exp":"Puede votar en las elecciones para influir.","phrase":"Rätt! Genom att rösta kan man påverka.","why":"En democracia, votar es la forma principal de influir; también puede afiliarse a un partido, manifestarse o expresar su opinión libremente."},
        {"q":"Vad är allmän rösträtt?","qEs":"¿Qué es el sufragio universal?","options":["Bara rika får rösta","Alla vuxna medborgare får rösta","Bara politiker får rösta","Bara män får rösta"],"correct":1,"exp":"Significa que todos los ciudadanos adultos pueden votar.","phrase":"Rätt! Allmän rösträtt betyder att alla vuxna får rösta."},
        {"q":"Vad är yttrandefrihet?","qEs":"¿Qué es la libertad de expresión?","options":["Rätten att uttrycka sina åsikter","Rätten till gratis mat","Rätten att köra bil","Rätten att inte betala skatt"],"correct":0,"exp":"Es el derecho a expresar tus opiniones libremente.","phrase":"Rätt! Yttrandefrihet är rätten att säga sin åsikt."},
        {"q":"Vem har makten i en demokrati?","qEs":"¿Quién tiene el poder en una democracia?","options":["Kungen","Armén","Domstolarna","Folket"],"correct":3,"exp":"En una democracia el poder pertenece al pueblo.","phrase":"Rätt! I en demokrati har folket makten."},
        {"q":"Vad kallas det när folket får rösta om en särskild fråga?","qEs":"¿Cómo se llama cuando el pueblo vota sobre una cuestión concreta?","options":["Diktatur","Anarki","Monarki","Folkomröstning"],"correct":3,"exp":"Se llama referéndum (folkomröstning).","phrase":"Rätt! Det kallas folkomröstning."},
        {"q":"En person tycker att ett politiskt beslut är fel. Vad kan hen göra i en demokrati?","qEs":"Una persona cree que una decisión política está mal. ¿Qué puede hacer en una democracia?","options":["Använda våld","Muta en politiker","Protestera fredligt och rösta i nästa val","Inget alls"],"correct":2,"isCase":true,"exp":"Puede protestar pacíficamente y votar en las próximas elecciones.","phrase":"Rätt! Man kan protestera fredligt och rösta.","why":"En una democracia se cambian las cosas participando: manifestándose pacíficamente, escribiendo, organizándose y votando, no con violencia."}
      ]
    },
    {
      id: "m03", title: "Hur Sverige styrs", active: true,
      aprende: "Suecia se gobierna en tres niveles: el Estado (**stat**), la región (**region**) y el municipio (**kommun**). El parlamento, el Riksdag (**Riksdag**), aprueba las leyes (**stiftar lagar**). El gobierno (**regering**), dirigido por el primer ministro (**statsminister**), dirige el país y ejecuta las leyes. El sector público (**offentlig sektor**) ofrece escuela, sanidad y cuidados, y se financia con impuestos (**skatt**). Los municipios se encargan de servicios locales como la escuela y el cuidado de mayores. El Riksdag se elige cada cuatro años.",
      palabras: [{"sv":"Riksdag","es":"parlamento"},{"sv":"regering","es":"gobierno"},{"sv":"statsminister","es":"primer ministro"},{"sv":"kommun","es":"municipio"},{"sv":"offentlig sektor","es":"sector público"},{"sv":"stifta lagar","es":"legislar"}],
      questions: [
        {"q":"Vem stiftar lagar i Sverige?","qEs":"¿Quién hace las leyes en Suecia?","options":["Kommunen","Kungen","Riksdagen","Domstolen"],"correct":2,"exp":"El Riksdag (parlamento) hace las leyes.","phrase":"Rätt! Riksdagen stiftar lagarna.","why":"El Riksdag es el poder legislativo; el gobierno ejecuta las leyes y los tribunales juzgan."},
        {"q":"Vem leder regeringen?","qEs":"¿Quién dirige el gobierno?","options":["Kungen","Talmannen","Presidenten","Statsministern"],"correct":3,"exp":"El gobierno lo dirige el primer ministro (statsminister).","phrase":"Rätt! Statsministern leder regeringen."},
        {"q":"Vad är den offentliga sektorns huvuduppgift?","qEs":"¿Cuál es la función principal del sector público?","options":["Sälja varor","Ge välfärd som skola och vård","Styra företag","Göra vinst"],"correct":1,"exp":"La función principal del sector público es dar bienestar: escuela, sanidad y cuidados.","phrase":"Rätt! Den offentliga sektorn ger välfärd.","why":"El sector público, financiado con impuestos, provee servicios como escuela, sanidad y asistencia social; no busca lucro."},
        {"q":"Vad ansvarar kommunen för?","qEs":"¿De qué se encarga el municipio?","options":["Försvaret","Riksbanken","Skola och äldreomsorg","Utrikespolitik"],"correct":2,"exp":"El municipio se encarga de la escuela y del cuidado de mayores, entre otros servicios locales.","phrase":"Rätt! Kommunen ansvarar för skola och omsorg."},
        {"q":"Hur ofta hålls riksdagsval i Sverige?","qEs":"¿Cada cuánto se celebran elecciones al parlamento en Suecia?","options":["Vart tionde år","Vartannat år","Vart fjärde år","Varje år"],"correct":2,"exp":"Las elecciones al Riksdag se celebran cada cuatro años.","phrase":"Rätt! Riksdagsval hålls vart fjärde år."},
        {"q":"En person undrar vem som bestämmer om kommunalskatten. Vad är rätt?","qEs":"Una persona se pregunta quién decide el impuesto municipal. ¿Qué es correcto?","options":["Kungen","Företagen","Riksdagen ensam","Kommunfullmäktige"],"correct":3,"isCase":true,"exp":"El pleno municipal (kommunfullmäktige) decide el impuesto municipal.","phrase":"Rätt! Kommunfullmäktige bestämmer kommunalskatten.","why":"Cada municipio tiene una asamblea elegida (kommunfullmäktige) que decide sobre los servicios locales y el impuesto municipal."},
        {"q":"Hur många ledamöter har riksdagen?","qEs":"¿Cuántos miembros tiene el Parlamento (riksdagen)?","options":["349","200","500","100"],"correct":0,"exp":"El Riksdag tiene 349 miembros.","phrase":"Rätt! Riksdagen har 349 ledamöter."},
        {"q":"Vad heter Sveriges regeringschef?","qEs":"¿Cómo se llama el jefe de gobierno de Suecia?","options":["Borgmästare","Kung","President","Statsminister"],"correct":3,"exp":"El jefe de gobierno es el primer ministro (statsminister).","phrase":"Rätt! Regeringschefen kallas statsminister."},
        {"q":"Vilken nivå ansvarar oftast för sjukvården i Sverige?","qEs":"¿Qué nivel se encarga normalmente de la sanidad en Suecia?","options":["Regionen","Kungen","Kommunen","Riksdagen"],"correct":0,"exp":"Las regiones (regioner) son responsables de la sanidad.","phrase":"Rätt! Regionen ansvarar för sjukvården."},
        {"q":"Vad gör riksdagen?","qEs":"¿Qué hace el Parlamento (riksdagen)?","options":["Väljer kungen","Dömer brottslingar","Stiftar lagar och beslutar om statens budget","Leder polisen"],"correct":2,"exp":"El Riksdag hace las leyes y decide el presupuesto del Estado.","phrase":"Rätt! Riksdagen stiftar lagar och beslutar om budgeten."}
      ]
    },
    {
      id: "m04", title: "Val och politik", active: true,
      aprende: "En Suecia hay elecciones (**val**) cada cuatro años para el Riksdag, las regiones y los municipios. Los ciudadanos votan por partidos (**partier**), no por personas concretas. El partido o la coalición (**koalition**) con mayoría forma el gobierno. El voto es libre y secreto. Los partidos que no gobiernan forman la oposición (**oppositionen**), que controla al gobierno y propone alternativas. También hay elecciones al Parlamento Europeo. En la papeleta (**valsedel**) se elige el partido.",
      palabras: [{"sv":"val","es":"elección"},{"sv":"parti","es":"partido"},{"sv":"valsedel","es":"papeleta"},{"sv":"koalition","es":"coalición"},{"sv":"oppositionen","es":"la oposición"},{"sv":"riksdagsval","es":"elección parlamentaria"}],
      questions: [
        {"q":"Vad röstar man på i ett svenskt val?","qEs":"¿A qué se vota en una elección sueca?","options":["Partier","Företag","Domstolar","Kungar"],"correct":0,"exp":"En Suecia se vota por partidos.","phrase":"Rätt! Man röstar på partier."},
        {"q":"Vad kallas partierna som inte sitter i regeringen?","qEs":"¿Cómo se llaman los partidos que no están en el gobierno?","options":["Kungahuset","Oppositionen","Regeringen","Majoriteten"],"correct":1,"exp":"Los partidos que no están en el gobierno forman la oposición.","phrase":"Rätt! De kallas oppositionen.","why":"La oposición controla al gobierno y propone alternativas; es esencial en una democracia."},
        {"q":"Är röstningen i Sverige hemlig?","qEs":"¿El voto en Suecia es secreto?","options":["Ja, den är hemlig","Bara för vissa","Nej, alla ser den","Man röstar öppet"],"correct":0,"exp":"Sí, el voto es secreto.","phrase":"Rätt! Röstningen är hemlig."},
        {"q":"Vilket val hålls också i Sverige förutom riksdagsvalet?","qEs":"¿Qué elección también se celebra en Suecia además de la parlamentaria?","options":["Val av domare","Val av kung","Val av polischef","Val till Europaparlamentet"],"correct":3,"exp":"También hay elecciones al Parlamento Europeo.","phrase":"Rätt! Man röstar också till Europaparlamentet.","why":"Como miembro de la UE, Suecia elige a sus representantes en el Parlamento Europeo cada cinco años."},
        {"q":"En person är 17 år och vill rösta i riksdagsvalet. Får hen det?","qEs":"Una persona tiene 17 años y quiere votar en las elecciones parlamentarias. ¿Puede?","options":["Ja, alla får","Ja, från 15 år","Nej, man måste vara 18","Bara med tillstånd"],"correct":2,"isCase":true,"exp":"No; hay que tener 18 años para votar.","phrase":"Rätt! Man måste vara 18 år för att rösta."},
        {"q":"Hur ofta är det val till riksdag, region och kommun i Sverige?","qEs":"¿Cada cuánto hay elecciones al parlamento, la región y el municipio en Suecia?","options":["Vartannat år","Varje år","Vart sjätte år","Vart fjärde år"],"correct":3,"exp":"Cada cuatro años, el mismo día.","phrase":"Rätt! Det är val vart fjärde år."},
        {"q":"Vad är ett politiskt parti?","qEs":"¿Qué es un partido político?","options":["En grupp människor med liknande idéer om samhället","Ett företag","En religion","En sportklubb"],"correct":0,"exp":"Es un grupo de personas con ideas parecidas sobre la sociedad.","phrase":"Rätt! Ett parti är en grupp med gemensamma idéer."},
        {"q":"Vad krävs för att få rösta i riksdagsvalet?","qEs":"¿Qué se necesita para votar en las elecciones al parlamento?","options":["Svenskt medborgarskap och fyllda 18 år","Att vara man","Att bo i Stockholm","Att vara rik"],"correct":0,"exp":"Ciudadanía sueca y haber cumplido 18 años.","phrase":"Rätt! Man behöver medborgarskap och vara 18 år."},
        {"q":"Får personer utan svenskt medborgarskap rösta i kommunalvalet?","qEs":"¿Pueden votar en las elecciones municipales las personas sin ciudadanía sueca?","options":["Ja, om de bott i Sverige tillräckligt länge","Bara i riksdagsval","Bara kungen får rösta","Nej, aldrig"],"correct":0,"exp":"Sí, tras vivir en Suecia el tiempo requerido pueden votar en elecciones locales.","phrase":"Rätt! Man kan rösta i kommunalval efter en tid i Sverige."},
        {"q":"En person vill starta ett nytt politiskt parti. Får hen det i Sverige?","qEs":"Una persona quiere crear un nuevo partido político. ¿Puede hacerlo en Suecia?","options":["Bara med tillstånd från polisen","Bara kungen får","Ja, man får bilda partier fritt","Nej, det är förbjudet"],"correct":2,"isCase":true,"exp":"Sí, en Suecia se pueden formar partidos libremente.","phrase":"Rätt! Man får bilda politiska partier fritt.","why":"La libertad de asociación y de organización política es parte de la democracia sueca; cualquiera puede fundar un partido."}
      ]
    },
    {
      id: "m05", title: "Lagar och rättssystemet", active: true,
      aprende: "En Suecia todos son iguales ante la ley (**lag**). La policía (**polis**) mantiene el orden e investiga delitos (**brott**); los tribunales (**domstol**) juzgan de forma independiente y nadie es culpable hasta que se demuestre. Existe libertad de expresión (**yttrandefrihet**), pero con límites: amenazar, difamar o incitar al odio contra un grupo (**hets mot folkgrupp**) es delito. Las leyes protegen tanto los derechos como los deberes de las personas. El sistema judicial (**rättssystem**) garantiza un proceso justo.",
      palabras: [{"sv":"lag","es":"ley"},{"sv":"domstol","es":"tribunal"},{"sv":"polis","es":"policía"},{"sv":"brott","es":"delito"},{"sv":"yttrandefrihet","es":"libertad de expresión"},{"sv":"hets mot folkgrupp","es":"incitación al odio"}],
      questions: [
        {"q":"Vem dömer i brottmål i Sverige?","qEs":"¿Quién juzga los delitos en Suecia?","options":["Domstolen","Riksdagen","Kungen","Polisen"],"correct":0,"exp":"Los tribunales juzgan los delitos.","phrase":"Rätt! Domstolen dömer i brottmål.","why":"La policía investiga, la fiscalía acusa y el tribunal (domstol) juzga de forma independiente."},
        {"q":"Vad gäller inför lagen i Sverige?","qEs":"¿Qué rige ante la ley en Suecia?","options":["Män har mer rätt","Alla är lika","Kungen står över lagen","Rika har mer rätt"],"correct":1,"exp":"Todos son iguales ante la ley.","phrase":"Rätt! Alla är lika inför lagen."},
        {"q":"Får man säga vad man vill i Sverige?","qEs":"¿Se puede decir lo que uno quiera en Suecia?","options":["Ja, men hets mot folkgrupp är förbjudet","Bara politiker får","Ja, allt är tillåtet","Nej, ingenting"],"correct":0,"exp":"Hay libertad de expresión, pero incitar al odio contra un grupo está prohibido.","phrase":"Rätt! Yttrandefrihet finns, men hets mot folkgrupp är olagligt.","why":"La libertad de expresión es amplia, pero tiene límites: las amenazas, la difamación y la incitación al odio (hets mot folkgrupp) son delitos."},
        {"q":"En person publicerar en åsikt i sociala medier. Vad säger svensk lag?","qEs":"Una persona publica una opinión en redes sociales. ¿Qué dice la ley sueca?","options":["Man måste fråga polisen först","Allt är förbjudet","Bara positiva åsikter är tillåtna","Det är tillåtet, men man får inte hetsa mot en folkgrupp"],"correct":3,"isCase":true,"exp":"Publicar una opinión está permitido por la libertad de expresión, pero no se puede incitar al odio contra un grupo.","phrase":"Rätt! Åsikter är tillåtna, men inte hets mot folkgrupp.","why":"En redes sociales también rige la libertad de expresión; sin embargo, las amenazas, la difamación o la incitación al odio (hets mot folkgrupp) siguen siendo delitos."},
        {"q":"Vad gör polisen i Sverige?","qEs":"¿Qué hace la policía en Suecia?","options":["Styr landet","Upprätthåller ordning och utreder brott","Stiftar lagar","Dömer folk"],"correct":1,"exp":"La policía mantiene el orden e investiga delitos.","phrase":"Rätt! Polisen upprätthåller ordning och utreder brott."},
        {"q":"Vad är en domstol?","qEs":"¿Qué es un tribunal (domstol)?","options":["En plats där rättsliga tvister och brott avgörs","En skola","Ett sjukhus","En bank"],"correct":0,"exp":"Es el lugar donde se resuelven conflictos legales y delitos.","phrase":"Rätt! I domstolen avgörs rättsliga frågor."},
        {"q":"Vad kan hända om man bryter mot lagen i Sverige?","qEs":"¿Qué puede pasar si infringes la ley en Suecia?","options":["Man blir kung","Man får en present","Man kan dömas till straff, t.ex. böter eller fängelse","Ingenting"],"correct":2,"exp":"Puedes ser condenado a una pena, como multa o cárcel.","phrase":"Rätt! Man kan dömas till böter eller fängelse."},
        {"q":"Är det tillåtet att slå barn (barnaga) i Sverige?","qEs":"¿Está permitido pegar a los niños en Suecia?","options":["Nej, det är förbjudet i lag","Ja, det är tillåtet","Bara i skolan","Bara ibland"],"correct":0,"exp":"No. Suecia prohibió el castigo físico a los niños en 1979.","phrase":"Rätt! Barnaga är förbjudet i Sverige."},
        {"q":"Vad menas med att man är oskyldig tills motsatsen bevisats?","qEs":"¿Qué significa que uno es inocente hasta que se demuestre lo contrario?","options":["Man måste bevisa sin egen oskuld","Man är alltid skyldig","Man ses som oskyldig tills skulden bevisats i domstol","Polisen bestämmer straffet"],"correct":2,"exp":"Se te considera inocente hasta que el tribunal demuestre la culpa.","phrase":"Rätt! Man är oskyldig tills skulden bevisats."},
        {"q":"Vem ser till att lagarna följs i samhället?","qEs":"¿Quién se asegura de que se cumplan las leyes en la sociedad?","options":["Bara grannarna","Bara kungen","Polisen och domstolarna","Ingen"],"correct":2,"exp":"La policía y los tribunales velan por el cumplimiento de la ley.","phrase":"Rätt! Polisen och domstolarna upprätthåller lagen."}
      ]
    },
    {
      id: "m06", title: "Medier", active: true,
      aprende: "En Suecia hay libertad de prensa (**tryckfrihet**) y libertad de expresión. Los medios (**medier**) —prensa, radio, TV e internet— informan y fiscalizan a quienes tienen el poder; por eso se les llama el \"tercer poder\". El servicio público (**public service**), como SVT y Sveriges Radio, se financia de forma pública y debe ser independiente e imparcial. La crítica de fuentes (**källkritik**) es clave: comprobar si una información es fiable antes de creerla o compartirla. Además, el principio de acceso público permite a cualquiera consultar documentos oficiales.",
      palabras: [{"sv":"medier","es":"medios"},{"sv":"tryckfrihet","es":"libertad de prensa"},{"sv":"källkritik","es":"crítica de fuentes"},{"sv":"public service","es":"servicio público"},{"sv":"nyheter","es":"noticias"},{"sv":"yttrandefrihet","es":"libertad de expresión"}],
      questions: [
        {"q":"Vad är massmediernas viktiga roll i en demokrati?","qEs":"¿Cuál es el papel importante de los medios en una democracia?","options":["Att döma brott","Att sälja varor","Att styra landet","Att granska makten och informera"],"correct":3,"exp":"Su papel clave es informar y fiscalizar (controlar) al poder.","phrase":"Rätt! Medier granskar makten och informerar.","why":"En una democracia, los medios libres informan y vigilan a quienes tienen el poder; por eso se les llama el \"tercer poder\"."},
        {"q":"Vad betyder tryckfrihet?","qEs":"¿Qué significa libertad de prensa?","options":["Att allt är gratis","Rätten att publicera utan censur","Att staten styr tidningarna","Förbud mot tidningar"],"correct":1,"exp":"Libertad de prensa: derecho a publicar sin censura.","phrase":"Rätt! Tryckfrihet är rätten att publicera fritt."},
        {"q":"Vad är källkritik?","qEs":"¿Qué es la crítica de fuentes?","options":["Att undvika nyheter","Att kritisera alla","Att tro på allt","Att granska om information är pålitlig"],"correct":3,"exp":"Crítica de fuentes: examinar si la información es fiable.","phrase":"Rätt! Källkritik är att granska informationens tillförlitlighet.","why":"Ante tanta información (y desinformación), es clave comprobar quién dice algo, cuándo y por qué antes de creerlo."},
        {"q":"Vad är exempel på public service i Sverige?","qEs":"¿Qué es un ejemplo de servicio público en Suecia?","options":["SVT och Sveriges Radio","Privata bloggar","Reklamföretag","Netflix"],"correct":0,"exp":"SVT y Sveriges Radio son servicio público.","phrase":"Rätt! SVT och SR är public service."},
        {"q":"En person läser en sensationell nyhet på nätet. Vad är klokt att göra?","qEs":"Una persona lee una noticia sensacionalista en internet. ¿Qué es sensato hacer?","options":["Dela den direkt","Ignorera all information","Tro på allt","Kontrollera källan innan man tror på den"],"correct":3,"isCase":true,"exp":"Lo sensato es comprobar la fuente antes de creerla o compartirla.","phrase":"Rätt! Man bör kontrollera källan först.","why":"La crítica de fuentes (källkritik) evita difundir desinformación: verifica el origen y contrástalo con medios fiables."},
        {"q":"Vad betyder fri press?","qEs":"¿Qué significa prensa libre?","options":["Medier kan rapportera och granska makthavare fritt","Staten bestämmer allt som skrivs","Ingen får skriva nyheter","Bara kungen får ge nyheter"],"correct":0,"exp":"Los medios pueden informar y fiscalizar al poder sin censura.","phrase":"Rätt! Fri press granskar makten fritt."},
        {"q":"Vad betyder det att vara källkritisk på internet?","qEs":"¿Qué significa ser crítico con las fuentes en internet?","options":["Att tro på allt","Att aldrig läsa nyheter","Att bara läsa rubriker","Att kontrollera om informationen stämmer och varifrån den kommer"],"correct":3,"exp":"Es comprobar si la información es cierta y de dónde viene.","phrase":"Rätt! Källkritik betyder att kontrollera informationen."},
        {"q":"Vad är desinformation?","qEs":"¿Qué es la desinformación?","options":["Sann och kontrollerad information","Sportresultat","Falsk information som sprids medvetet för att vilseleda","Väderrapporter"],"correct":2,"exp":"Es información falsa que se difunde a propósito para engañar.","phrase":"Rätt! Desinformation är medveten falsk information."},
        {"q":"Vem betalar för public service (SVT och SR)?","qEs":"¿Quién paga el servicio público (SVT y SR)?","options":["Alla medborgare via skatten","Bara kungen","Ingen","Bara reklamföretag"],"correct":0,"exp":"Se financia con impuestos, por eso es independiente de la publicidad.","phrase":"Rätt! Public service betalas via skatten."},
        {"q":"Du ser en nyhet utan känd källa på sociala medier. Vad bör du göra?","qEs":"Ves una noticia sin fuente conocida en redes sociales. ¿Qué deberías hacer?","options":["Kontrollera fakta i pålitliga källor innan du sprider den","Tro på den utan att tänka","Dela den direkt","Bli arg på alla"],"correct":0,"isCase":true,"exp":"Comprobar los hechos en fuentes fiables antes de compartir.","phrase":"Rätt! Kontrollera fakta innan du delar.","why":"La desinformación se propaga cuando la gente comparte sin verificar. Ser crítico con las fuentes protege a todos."}
      ]
    },
    {
      id: "m07", title: "Mänskliga rättigheter", active: true,
      aprende: "Los derechos humanos (**mänskliga rättigheter**) pertenecen a todas las personas, sin importar su origen, religión, sexo u opinión. Suecia los protege y ha firmado convenios internacionales de la ONU. Principios clave: el igual valor de todas las personas (**alla människors lika värde**), la libertad de religión (**religionsfrihet**), la libertad de expresión y la protección frente a la discriminación (**diskriminering**). Los niños tienen derechos especiales (la Convención del Niño, **barnkonventionen**). La igualdad entre mujeres y hombres (**jämställdhet**) es un valor central en la sociedad sueca.",
      palabras: [{"sv":"mänskliga rättigheter","es":"derechos humanos"},{"sv":"lika värde","es":"igual valor"},{"sv":"religionsfrihet","es":"libertad de religión"},{"sv":"diskriminering","es":"discriminación"},{"sv":"jämställdhet","es":"igualdad de género"},{"sv":"barnkonventionen","es":"Convención del Niño"}],
      questions: [
        {"q":"Vem har mänskliga rättigheter?","qEs":"¿Quién tiene derechos humanos?","options":["Bara vuxna","Bara svenskar","Bara medborgare","Alla människor"],"correct":3,"exp":"Todas las personas tienen derechos humanos.","phrase":"Rätt! Alla människor har mänskliga rättigheter.","why":"Los derechos humanos son universales: valen para todos por el hecho de ser personas."},
        {"q":"Vad betyder religionsfrihet?","qEs":"¿Qué significa libertad de religión?","options":["Alla måste ha en religion","Förbud mot religion","Rätten att tro eller inte tro","Bara en religion tillåts"],"correct":2,"exp":"Libertad de religión: derecho a creer o no creer.","phrase":"Rätt! Religionsfrihet betyder att man får tro eller inte tro."},
        {"q":"Vad är diskriminering?","qEs":"¿Qué es la discriminación?","options":["Att betala skatt","Att alla är lika","Att behandla någon sämre på grund av t.ex. kön eller ursprung","Att hjälpa någon"],"correct":2,"exp":"Discriminación: tratar peor a alguien por su sexo, origen, etc.","phrase":"Rätt! Diskriminering är att behandla någon orättvist.","why":"En Suecia la discriminación por sexo, origen, religión, discapacidad u orientación está prohibida por ley."},
        {"q":"Vad menas med jämställdhet?","qEs":"¿Qué significa igualdad de género?","options":["Lika rättigheter för kvinnor och män","Att män bestämmer","Att kvinnor bestämmer","Ingen jämlikhet"],"correct":0,"exp":"Igualdad de género: iguales derechos para mujeres y hombres.","phrase":"Rätt! Jämställdhet är lika rättigheter för kvinnor och män."},
        {"q":"En arbetsgivare vägrar anställa en person på grund av dess religion. Vad gäller?","qEs":"Un empleador se niega a contratar a alguien por su religión. ¿Qué rige?","options":["Man måste byta religion","Det är olaglig diskriminering","Det bestämmer arbetsgivaren fritt","Det är tillåtet"],"correct":1,"isCase":true,"exp":"Es discriminación ilegal negar un empleo por la religión.","phrase":"Rätt! Det är olaglig diskriminering.","why":"La ley de discriminación (diskrimineringslagen) prohíbe rechazar a alguien por motivos como religión, sexo u origen."},
        {"q":"Vad är en grundläggande mänsklig rättighet?","qEs":"¿Qué es un derecho humano fundamental?","options":["Rätten till liv, frihet och personlig säkerhet","Rätten att inte arbeta","Rätten till lyx","Rätten att bryta mot lagen"],"correct":0,"exp":"El derecho a la vida, la libertad y la seguridad personal.","phrase":"Rätt! Rätten till liv och frihet är grundläggande."},
        {"q":"Är alla människor lika mycket värda enligt de mänskliga rättigheterna?","qEs":"Según los derechos humanos, ¿todas las personas valen lo mismo?","options":["Nej, bara vissa","Bara svenskar","Bara rika","Ja, alla människor är lika i värde och rättigheter"],"correct":3,"exp":"Sí, todas las personas son iguales en dignidad y derechos.","phrase":"Rätt! Alla människor är lika mycket värda."},
        {"q":"Vilka rättigheter skyddas av barnkonventionen?","qEs":"¿Qué derechos protege la Convención sobre los Derechos del Niño?","options":["Bara vuxnas rättigheter","Barns rättigheter","Djurens rättigheter","Företagens rättigheter"],"correct":1,"exp":"Protege los derechos de los niños; es ley en Suecia desde 2020.","phrase":"Rätt! Barnkonventionen skyddar barns rättigheter."},
        {"q":"Vad betyder yttrandefrihet som mänsklig rättighet?","qEs":"¿Qué significa la libertad de expresión como derecho humano?","options":["Rätten att slåss","Rätten att ljuga i domstol","Rätten att fritt uttrycka åsikter och tankar","Rätten att tvinga andra"],"correct":2,"exp":"El derecho a expresar libremente opiniones y pensamientos.","phrase":"Rätt! Yttrandefrihet är en mänsklig rättighet."},
        {"q":"Vilka rättigheter har hbtq-personer i Sverige?","qEs":"¿Qué derechos tienen las personas LGTBQ en Suecia?","options":["Bara vissa rättigheter","Inga rättigheter","Färre rättigheter","Samma rättigheter som alla andra, t.ex. att gifta sig"],"correct":3,"exp":"Tienen los mismos derechos que todos, incluido casarse.","phrase":"Rätt! Hbtq-personer har samma rättigheter som alla."}
      ]
    },
    {
      id: "m08", title: "Arbete och ekonomi", active: true,
      aprende: "En Suecia la mayoría de los adultos trabaja (**arbeta**) y paga impuestos (**skatt**) sobre sus ingresos (**inkomst**); esos impuestos financian el bienestar. El mercado laboral (**arbetsmarknad**) tiene reglas: un contrato de trabajo (**anställningsavtal**), sindicatos (**fackförbund**) que defienden a los trabajadores, y derechos como vacaciones y lugares de trabajo seguros. Ante el desempleo (**arbetslöshet**) hay ayudas. La agencia pública de empleo (**Arbetsförmedlingen**) ayuda a encontrar trabajo y ofrece orientación y formación.",
      palabras: [{"sv":"arbete","es":"trabajo"},{"sv":"inkomst","es":"ingreso"},{"sv":"skatt","es":"impuesto"},{"sv":"fackförbund","es":"sindicato"},{"sv":"anställningsavtal","es":"contrato de trabajo"},{"sv":"arbetslöshet","es":"desempleo"}],
      questions: [
        {"q":"Vad betalar man skatt på i Sverige?","qEs":"¿Sobre qué se paga impuesto en Suecia?","options":["Ingenting","Bara på lyxvaror","Sin inkomst","Bara företag betalar"],"correct":2,"exp":"Se paga impuesto sobre los ingresos.","phrase":"Rätt! Man betalar skatt på sin inkomst.","why":"Los impuestos financian la sanidad, la escuela y el bienestar; casi todos los que trabajan contribuyen."},
        {"q":"Vad gör ett fackförbund?","qEs":"¿Qué hace un sindicato?","options":["Dömer brott","Styr landet","Företräder och skyddar arbetstagarna","Säljer varor"],"correct":2,"exp":"Un sindicato representa y protege a los trabajadores.","phrase":"Rätt! Ett fackförbund företräder arbetstagarna.","why":"Los sindicatos negocian salarios y condiciones y defienden los derechos de los empleados."},
        {"q":"Vad behöver man oftast för att jobba i Sverige?","qEs":"¿Qué se necesita normalmente para trabajar en Suecia?","options":["Bara pengar","Ett körkort","Ett anställningsavtal","Ingenting"],"correct":2,"exp":"Normalmente se necesita un contrato de trabajo.","phrase":"Rätt! Man behöver ett anställningsavtal."},
        {"q":"Vad kallas det när man inte har ett jobb?","qEs":"¿Cómo se llama cuando no se tiene trabajo?","options":["Pension","Arbetslöshet","Semester","Inkomst"],"correct":1,"exp":"Se llama desempleo (arbetslöshet).","phrase":"Rätt! Att sakna jobb kallas arbetslöshet."},
        {"q":"En person söker jobb i Sverige. Vilken myndighet kan hjälpa till?","qEs":"Una persona busca trabajo en Suecia. ¿Qué organismo puede ayudar?","options":["Polisen","Arbetsförmedlingen","Migrationsverket","Skatteverket"],"correct":1,"isCase":true,"exp":"El Servicio de Empleo (Arbetsförmedlingen) ayuda a buscar trabajo.","phrase":"Rätt! Arbetsförmedlingen hjälper till att hitta jobb.","why":"Arbetsförmedlingen es la agencia pública de empleo: orienta, ofrece formación y conecta con empleadores."},
        {"q":"Vad är ett kollektivavtal?","qEs":"¿Qué es un convenio colectivo?","options":["En lag om trafik","Ett bankkonto","En skatt","Ett avtal om löner och arbetsvillkor mellan fack och arbetsgivare"],"correct":3,"exp":"Es un acuerdo sobre salarios y condiciones entre sindicato y empleador.","phrase":"Rätt! Kollektivavtal reglerar löner och villkor."},
        {"q":"Vad används skattepengarna till i Sverige?","qEs":"¿Para qué se usa el dinero de los impuestos en Suecia?","options":["Bara kungens lön","Ingenting","Bara militären","Skola, sjukvård, vägar och välfärd"],"correct":3,"exp":"Para escuela, sanidad, carreteras y bienestar social.","phrase":"Rätt! Skatten finansierar välfärden."},
        {"q":"Vad är a-kassa?","qEs":"¿Qué es la \"a-kassa\" (caja de desempleo)?","options":["Ekonomisk ersättning om man blir arbetslös","Pension","Barnbidrag","Pengar när man är sjuk"],"correct":0,"exp":"Es una compensación económica si te quedas sin trabajo.","phrase":"Rätt! A-kassa ger ersättning vid arbetslöshet."},
        {"q":"Behöver man betala skatt på sin lön i Sverige?","qEs":"¿Hay que pagar impuestos sobre el salario en Suecia?","options":["Bara rika betalar","Bara företag betalar","Nej, aldrig","Ja, man betalar inkomstskatt på sin lön"],"correct":3,"exp":"Sí, se paga impuesto sobre la renta del salario.","phrase":"Rätt! Man betalar inkomstskatt på lönen."},
        {"q":"En person tycker att lönen är fel och villkoren dåliga på jobbet. Vart kan hen vända sig?","qEs":"Una persona cree que su salario está mal y las condiciones son malas. ¿A dónde puede acudir?","options":["Ingenstans","Till kungen","Till polisen","Till sitt fackförbund"],"correct":3,"isCase":true,"exp":"Puede acudir a su sindicato (fackförbund).","phrase":"Rätt! Facket hjälper med löner och villkor.","why":"Los sindicatos negocian y defienden los derechos de los trabajadores en el mercado laboral sueco."}
      ]
    },
    {
      id: "m09", title: "Välfärd", active: true,
      aprende: "El modelo de bienestar (**välfärd**) sueco da a todos acceso a la sanidad (**sjukvård**), la escuela (**skola**) y la seguridad social, financiado con impuestos. La atención sanitaria es en gran parte gratuita o de bajo coste. La escuela es gratuita y hay escolaridad obligatoria (**skolplikt**) para los niños. Existen ayudas por enfermedad, permiso parental (**föräldrapenning**), pensiones (**pension**) y apoyo a las familias. El objetivo es la seguridad (**trygghet**) y la igualdad de oportunidades para todas las personas.",
      palabras: [{"sv":"välfärd","es":"bienestar"},{"sv":"sjukvård","es":"sanidad"},{"sv":"skolplikt","es":"escolaridad obligatoria"},{"sv":"föräldrapenning","es":"prestación parental"},{"sv":"pension","es":"pensión"},{"sv":"trygghet","es":"seguridad"}],
      questions: [
        {"q":"Hur finansieras välfärden i Sverige?","qEs":"¿Cómo se financia el bienestar en Suecia?","options":["Med reklam","Med privata företag","Med skatter","Med lån från kungen"],"correct":2,"exp":"El bienestar se financia con impuestos.","phrase":"Rätt! Välfärden finansieras med skatter.","why":"Los impuestos que pagan quienes trabajan financian la sanidad, la escuela, las pensiones y las ayudas."},
        {"q":"Vad gäller för barn i Sverige när det gäller skola?","qEs":"¿Qué rige para los niños en Suecia respecto a la escuela?","options":["Skolan kostar mycket","Bara pojkar går i skolan","Det finns skolplikt","Skolan är frivillig"],"correct":2,"exp":"Existe escolaridad obligatoria (skolplikt) y la escuela es gratuita.","phrase":"Rätt! I Sverige finns skolplikt.","why":"Todos los niños tienen el derecho y la obligación de ir a la escuela, que es gratuita."},
        {"q":"Vad är föräldrapenning?","qEs":"¿Qué es la prestación parental (föräldrapenning)?","options":["Lön för att arbeta","En skatt","En pension","Ersättning när man är hemma med sitt barn"],"correct":3,"exp":"Prestación parental: dinero para estar en casa cuidando al hijo.","phrase":"Rätt! Föräldrapenning ger ersättning när man är hemma med barnet.","why":"Suecia tiene un permiso parental generoso, que ambos progenitores pueden compartir."},
        {"q":"Vad får man när man blir gammal och slutar arbeta?","qEs":"¿Qué se recibe al hacerse mayor y dejar de trabajar?","options":["Studielån","Pension","Böter","Barnbidrag"],"correct":1,"exp":"Al jubilarse se recibe una pensión (pension).","phrase":"Rätt! När man slutar arbeta får man pension."},
        {"q":"En person blir sjuk och kan inte arbeta en period. Vad kan hen få?","qEs":"Una persona se enferma y no puede trabajar un tiempo. ¿Qué puede recibir?","options":["Sjukpenning","Studielån","Ingenting","Böter"],"correct":0,"isCase":true,"exp":"Puede recibir un subsidio por enfermedad (sjukpenning).","phrase":"Rätt! Man kan få sjukpenning när man är sjuk.","why":"El seguro social (Försäkringskassan) paga sjukpenning cuando una enfermedad impide trabajar."},
        {"q":"Vad är barnbidrag?","qEs":"¿Qué es el \"barnbidrag\" (subsidio por hijos)?","options":["Pension","En skatt på barn","Ett bidrag till familjer för att ta hand om barn","Pengar bara till rika"],"correct":2,"exp":"Es una ayuda a las familias para el cuidado de los hijos.","phrase":"Rätt! Barnbidrag är stöd till familjer med barn."},
        {"q":"Är den kommunala skolan gratis i Sverige?","qEs":"¿Es gratuita la escuela pública en Suecia?","options":["Ja, den kommunala skolan är avgiftsfri","Nej, den kostar mycket","Bara för rika","Bara på sommaren"],"correct":0,"exp":"Sí, la escuela pública es gratuita.","phrase":"Rätt! Skolan är avgiftsfri."},
        {"q":"Vem har rätt till sjukvård i Sverige?","qEs":"¿Quién tiene derecho a la sanidad en Suecia?","options":["Bara rika","Alla som bor i Sverige","Bara svenska medborgare","Bara barn"],"correct":1,"exp":"Todas las personas que viven en Suecia.","phrase":"Rätt! Alla som bor i Sverige har rätt till sjukvård."},
        {"q":"Vad är pension?","qEs":"¿Qué es la pensión?","options":["En skatt","Lön för arbete","Ett lån","Pengar man får som gammal när man slutar arbeta"],"correct":3,"exp":"Es el dinero que recibes de mayor al dejar de trabajar.","phrase":"Rätt! Pension får man när man slutar arbeta."},
        {"q":"Vad är syftet med välfärdssamhället?","qEs":"¿Cuál es el objetivo del Estado de bienestar?","options":["Att straffa fattiga","Att bara hjälpa rika","Att ge trygghet och stöd till alla i samhället","Att spara pengar åt staten"],"correct":2,"exp":"Dar seguridad y apoyo a todas las personas de la sociedad.","phrase":"Rätt! Välfärden ger trygghet åt alla."}
      ]
    },
    {
      id: "m10", title: "Sveriges historia", active: true,
      aprende: "Suecia tiene una larga historia (**historia**). En la Edad Media ya era un reino. Durante varios siglos Finlandia (**Finland**) formó parte de Suecia, hasta 1809, cuando Suecia la perdió ante Rusia; por eso hoy hay suecoparlantes en Finlandia. En el siglo XIX muchos suecos emigraron (**utvandring**) a América huyendo de la pobreza. En el siglo XX el país se industrializó y construyó el Estado de bienestar (**välfärdsstat**), y se mantuvo neutral (**neutral**) en las dos guerras mundiales. Tras 1945 creció la inmigración (**invandring**) y Suecia se convirtió en una sociedad moderna y diversa. El sufragio universal llegó en 1921.",
      palabras: [{"sv":"historia","es":"historia"},{"sv":"Finland","es":"Finlandia"},{"sv":"neutral","es":"neutral"},{"sv":"utvandring","es":"emigración"},{"sv":"invandring","es":"inmigración"},{"sv":"välfärdsstat","es":"Estado de bienestar"}],
      questions: [
        {"q":"Vilket land var en del av Sverige i flera hundra år?","qEs":"¿Qué país fue parte de Suecia durante varios siglos?","options":["Norge","Danmark","Ryssland","Finland"],"correct":3,"exp":"Finlandia fue parte de Suecia durante varios siglos.","phrase":"Rätt! Finland var en del av Sverige i flera hundra år.","why":"Finlandia formó parte del reino de Suecia hasta 1809, cuando Suecia la perdió ante Rusia. Por eso comparten mucha historia y aún hay suecoparlantes en Finlandia."},
        {"q":"Vad gjorde Sverige under första och andra världskriget?","qEs":"¿Qué hizo Suecia durante la Primera y la Segunda Guerra Mundial?","options":["Anföll grannländer","Var neutralt","Blev ockuperat","Gick med i kriget"],"correct":1,"exp":"Suecia se mantuvo neutral en las dos guerras mundiales.","phrase":"Rätt! Sverige var neutralt under världskrigen."},
        {"q":"Vad hände i Sverige på 1900-talet?","qEs":"¿Qué pasó en Suecia en el siglo XX?","options":["Landet industrialiserades och byggde välfärd","Blev en koloni","Slutade med demokrati","Förlorade sin kung"],"correct":0,"exp":"En el siglo XX Suecia se industrializó y construyó el Estado de bienestar.","phrase":"Rätt! Sverige industrialiserades och byggde välfärdsstaten."},
        {"q":"Vad gjorde många svenskar på 1800-talet?","qEs":"¿Qué hicieron muchos suecos en el siglo XIX?","options":["Byggde pyramider","Invaderade Europa","Flyttade till Asien","Utvandrade till Amerika"],"correct":3,"exp":"En el siglo XIX muchos suecos emigraron a América por la pobreza.","phrase":"Rätt! Många svenskar utvandrade till Amerika.","why":"Entre 1850 y 1930, cerca de un millón de suecos emigraron (utvandring), sobre todo a EE. UU., huyendo del hambre y la pobreza."},
        {"q":"En person undrar varför det finns svensktalande i Finland. Vad är förklaringen?","qEs":"Una persona se pregunta por qué hay suecoparlantes en Finlandia. ¿Cuál es la explicación?","options":["Finland var en del av Sverige förr","Finland är en svensk koloni idag","De lärde sig svenska nyligen","Det är en slump"],"correct":0,"isCase":true,"exp":"Hay suecoparlantes en Finlandia porque Finlandia fue parte de Suecia.","phrase":"Rätt! Finland tillhörde Sverige förr, därför finns svensktalande där.","why":"Durante siglos Finlandia fue parte del reino sueco; por esa historia común, el sueco sigue siendo lengua oficial en Finlandia."},
        {"q":"Vilka var vikingarna?","qEs":"¿Quiénes eran los vikingos?","options":["Moderna soldater","Kungar från Finland","Ett politiskt parti","Nordbor som reste, handlade och plundrade under vikingatiden"],"correct":3,"exp":"Eran nórdicos que viajaban, comerciaban y saqueaban en la era vikinga.","phrase":"Rätt! Vikingarna var nordbor som reste och handlade."},
        {"q":"Har Sverige haft krig med sina grannländer förr?","qEs":"¿Ha tenido Suecia guerras con sus países vecinos antes?","options":["Bara med Tyskland","Bara på 2000-talet","Ja, Sverige har krigat med grannländerna genom historien","Nej, aldrig"],"correct":2,"exp":"Sí, Suecia guerreó con sus vecinos varias veces en la historia.","phrase":"Rätt! Sverige har haft krig med grannländerna."},
        {"q":"När blev Sverige ett industriland?","qEs":"¿Cuándo se convirtió Suecia en un país industrial?","options":["På medeltiden","År 2000","Under vikingatiden","Under 1800- och 1900-talet"],"correct":3,"exp":"Durante los siglos XIX y XX.","phrase":"Rätt! Sverige industrialiserades på 1800- och 1900-talet."},
        {"q":"Varför utvandrade många svenskar till USA på 1800-talet?","qEs":"¿Por qué muchos suecos emigraron a EE. UU. en el siglo XIX?","options":["På grund av krig i USA","På grund av fattigdom, svält och brist på arbete","För att de var rika","För semester"],"correct":1,"exp":"Por pobreza, hambre y falta de trabajo.","phrase":"Rätt! Många utvandrade på grund av fattigdom."},
        {"q":"Har Sverige deltagit i krig de senaste 200 åren?","qEs":"¿Ha participado Suecia en guerras en los últimos 200 años?","options":["Ja, i många krig","Nej, Sverige har haft fred i över 200 år","Bara andra världskriget","Bara första världskriget"],"correct":1,"exp":"No. Suecia ha tenido paz durante más de 200 años.","phrase":"Rätt! Sverige har haft fred i över 200 år."}
      ]
    },
    {
      id: "m11", title: "Sverige i världen", active: true,
      aprende: "Suecia forma parte de la comunidad internacional. Es miembro de la Unión Europea (**EU**) desde 1995 y de la ONU (**FN**). Trabaja por la paz, los derechos humanos y da ayuda al desarrollo (**bistånd**) a países más pobres. Mantuvo mucho tiempo la neutralidad, aunque recientemente se unió a la OTAN. El comercio (**handel**) con otros países es vital para su economía: exporta (**export**) coches, tecnología y productos forestales. Muchas empresas conocidas son suecas, como IKEA, Volvo y Spotify. La cooperación (**samarbete**) internacional es un valor importante.",
      palabras: [{"sv":"EU","es":"Unión Europea"},{"sv":"FN","es":"ONU"},{"sv":"handel","es":"comercio"},{"sv":"bistånd","es":"ayuda al desarrollo"},{"sv":"export","es":"exportación"},{"sv":"samarbete","es":"cooperación"}],
      questions: [
        {"q":"Vilken organisation är Sverige medlem i sedan 1995?","qEs":"¿De qué organización es miembro Suecia desde 1995?","options":["OPEC","EU","Afrikanska unionen","NASA"],"correct":1,"exp":"Suecia es miembro de la UE desde 1995.","phrase":"Rätt! Sverige är medlem i EU sedan 1995.","why":"Suecia entró en la Unión Europea en 1995 tras un referéndum, aunque mantiene su propia moneda."},
        {"q":"Vad står FN för?","qEs":"¿Qué significa FN?","options":["Fria Näringslivet","Förenta Nationerna","Företag och Näringsliv","Finska Nätverket"],"correct":1,"exp":"FN es la ONU (Förenta Nationerna, Naciones Unidas).","phrase":"Rätt! FN står för Förenta Nationerna."},
        {"q":"Vad är bistånd?","qEs":"¿Qué es la ayuda al desarrollo (bistånd)?","options":["Hjälp till fattigare länder","Ett företag","En lag","En skatt"],"correct":0,"exp":"Bistånd es la ayuda al desarrollo que se da a países más pobres.","phrase":"Rätt! Bistånd är hjälp till andra länder.","why":"Suecia dona una parte de su riqueza como ayuda al desarrollo, para reducir la pobreza y apoyar los derechos humanos en el mundo."},
        {"q":"Varför är handel viktig för Sverige?","qEs":"¿Por qué es importante el comercio para Suecia?","options":["Sverige exporterar varor och behöver andra länder","Bara för kungen","Sverige handlar inte","Sverige är självförsörjande"],"correct":0,"exp":"El comercio es clave: Suecia exporta y depende de otros países.","phrase":"Rätt! Handel med andra länder är viktig för ekonomin."},
        {"q":"En person vill veta om Sverige använder euro. Vad gäller?","qEs":"Una persona quiere saber si Suecia usa el euro. ¿Qué rige?","options":["Nej, Sverige använder svenska kronor","Ja, euro","Ja, dollar","Sverige har ingen valuta"],"correct":0,"isCase":true,"exp":"No; aunque está en la UE, Suecia usa la corona (krona), no el euro.","phrase":"Rätt! Sverige använder kronor, inte euro.","why":"Suecia es miembro de la UE pero decidió no adoptar el euro; mantiene su moneda nacional, la corona."},
        {"q":"När gick Sverige med i EU?","qEs":"¿Cuándo entró Suecia en la UE?","options":["1970","2010","1945","1995"],"correct":3,"exp":"Suecia entró en la Unión Europea en 1995.","phrase":"Rätt! Sverige gick med i EU 1995."},
        {"q":"Använder Sverige euro som valuta?","qEs":"¿Usa Suecia el euro como moneda?","options":["Ja, dollar","Nej, Sverige använder svenska kronor","Ja, euro","Sverige har ingen valuta"],"correct":1,"exp":"No, Suecia usa la corona sueca (kronor).","phrase":"Rätt! Sverige använder svenska kronor."},
        {"q":"Vad är Sverige känt för internationellt?","qEs":"¿Por qué es conocida Suecia internacionalmente?","options":["Krig","Vulkaner","Öknar","Miljöarbete, jämställdhet och innovation"],"correct":3,"exp":"Por su labor medioambiental, la igualdad y la innovación.","phrase":"Rätt! Sverige är känt för miljö, jämställdhet och innovation."},
        {"q":"Är Sverige medlem i FN?","qEs":"¿Es Suecia miembro de la ONU?","options":["Bara ibland","Sverige leder FN","Ja, Sverige är medlem i FN","Nej"],"correct":2,"exp":"Sí, Suecia es miembro de las Naciones Unidas.","phrase":"Rätt! Sverige är medlem i FN."},
        {"q":"En nyanländ undrar om Sverige samarbetar med andra länder. Vad stämmer?","qEs":"Un recién llegado se pregunta si Suecia coopera con otros países. ¿Qué es correcto?","options":["Ja, Sverige samarbetar genom EU, FN och internationell handel","Bara med USA","Bara med Norge","Nej, Sverige är isolerat"],"correct":0,"isCase":true,"exp":"Sí, coopera a través de la UE, la ONU y el comercio internacional.","phrase":"Rätt! Sverige samarbetar genom EU, FN och handel.","why":"Suecia es un país abierto que depende del comercio y participa activamente en organizaciones internacionales."}
      ]
    },
    {
      id: "m12", title: "Religion och mångfald", active: true,
      aprende: "En Suecia hay libertad de religión (**religionsfrihet**): cada persona puede creer o no creer. Históricamente el país fue cristiano luterano (la Iglesia de Suecia, **Svenska kyrkan**), pero hoy es una sociedad laica (**sekulärt**) y diversa (**mångfald**). Conviven muchas religiones —cristianismo, islam, judaísmo, budismo— y personas sin religión. La Iglesia y el Estado están separados desde el año 2000. El respeto y la tolerancia (**tolerans**) hacia las distintas creencias (**tro**) y culturas son valores fundamentales de la sociedad sueca.",
      palabras: [{"sv":"religionsfrihet","es":"libertad de religión"},{"sv":"Svenska kyrkan","es":"Iglesia de Suecia"},{"sv":"sekulärt","es":"laico"},{"sv":"mångfald","es":"diversidad"},{"sv":"tolerans","es":"tolerancia"},{"sv":"tro","es":"fe, creencia"}],
      questions: [
        {"q":"Vad innebär religionsfrihet i Sverige?","qEs":"¿Qué implica la libertad de religión en Suecia?","options":["Religion är förbjuden","Alla måste vara kristna","Man får tro eller inte tro","Bara en religion tillåts"],"correct":2,"exp":"Libertad de religión: se puede creer o no creer.","phrase":"Rätt! Religionsfrihet betyder att man får tro eller inte tro.","why":"En Suecia cada persona elige libremente su religión o no tener ninguna; el Estado no impone creencias."},
        {"q":"Vilken kyrka var statskyrka i Sverige förr?","qEs":"¿Qué iglesia fue iglesia estatal en Suecia antiguamente?","options":["Ortodoxa kyrkan","Svenska kyrkan","Katolska kyrkan","Ingen"],"correct":1,"exp":"La Iglesia de Suecia (luterana) fue la iglesia estatal.","phrase":"Rätt! Svenska kyrkan var statskyrka förr."},
        {"q":"Hur är det svenska samhället idag när det gäller religion?","qEs":"¿Cómo es la sociedad sueca hoy respecto a la religión?","options":["Sekulärt och mångkulturellt","Bara kristet","Utan religionsfrihet","Styrt av kyrkan"],"correct":0,"exp":"Hoy la sociedad es laica y multicultural.","phrase":"Rätt! Sverige är sekulärt och mångkulturellt.","why":"Aunque hay raíces cristianas, hoy conviven muchas religiones y muchas personas sin religión; Iglesia y Estado se separaron en el año 2000."},
        {"q":"Vad är viktigt i ett samhälle med mångfald?","qEs":"¿Qué es importante en una sociedad con diversidad?","options":["Tolerans och respekt","Att bara en kultur finns","Att förbjuda skillnader","Att alla är lika"],"correct":0,"exp":"La tolerancia y el respeto son clave en una sociedad diversa.","phrase":"Rätt! Tolerans och respekt är viktigt."},
        {"q":"En kollega firar en annan religiös högtid än du. Hur bör man agera i Sverige?","qEs":"Un colega celebra una fiesta religiosa distinta a la tuya. ¿Cómo se debe actuar en Suecia?","options":["Ignorera personen","Kräva att hen slutar","Anmäla till polisen","Respektera hens tro"],"correct":3,"isCase":true,"exp":"Lo correcto es respetar su creencia; existe libertad de religión.","phrase":"Rätt! Man respekterar andras tro.","why":"La libertad de religión y el respeto a la diversidad son valores fundamentales; cada persona puede practicar su fe libremente."},
        {"q":"Måste man tillhöra en religion i Sverige?","qEs":"¿Hay que pertenecer a una religión en Suecia?","options":["Ja, alla måste vara kristna","Bara barn måste","Ja, man måste välja en religion","Nej, man får själv välja att tro eller inte tro"],"correct":3,"exp":"No, cada persona decide libremente creer o no.","phrase":"Rätt! Man väljer själv att tro eller inte."},
        {"q":"Vilken religion har historiskt varit vanligast i Sverige?","qEs":"¿Qué religión ha sido históricamente la más común en Suecia?","options":["Buddhism","Islam","Hinduism","Kristendomen"],"correct":3,"exp":"El cristianismo (Iglesia de Suecia) ha sido el más común.","phrase":"Rätt! Kristendomen har varit vanligast historiskt."},
        {"q":"Får man byta eller lämna sin religion i Sverige?","qEs":"¿Se puede cambiar o dejar la religión en Suecia?","options":["Ja, alla får byta eller lämna sin religion","Bara en gång","Nej, det är förbjudet","Bara med tillstånd"],"correct":0,"exp":"Sí, es un derecho libre de cada persona.","phrase":"Rätt! Man får fritt byta eller lämna sin religion."},
        {"q":"Är Sverige ett mångkulturellt land idag?","qEs":"¿Es Suecia un país multicultural hoy?","options":["Bara européer","Nej, alla är lika","Ja, människor med olika bakgrund och kulturer bor här","Bara svenskar bor här"],"correct":2,"exp":"Sí, viven personas de muchos orígenes y culturas.","phrase":"Rätt! Sverige är ett mångkulturellt land."},
        {"q":"Är kyrka och stat åtskilda i Sverige idag?","qEs":"¿Están separadas la Iglesia y el Estado en Suecia hoy?","options":["Ja, sedan vikingatiden","Ja, Svenska kyrkan skildes från staten år 2000","Nej, kyrkan styr landet","Nej, aldrig"],"correct":1,"exp":"Sí, la Iglesia de Suecia se separó del Estado en el año 2000.","phrase":"Rätt! Kyrka och stat skildes år 2000."}
      ]
    },
    {
      id: "m13", title: "Kultur och traditioner", active: true,
      aprende: "Suecia tiene tradiciones (**traditioner**) ligadas a las estaciones. El midsommar (**midsommar**), en junio, celebra los días luminosos del verano con baile alrededor del \"majstång\". Lucia (**Lucia**), en diciembre, trae luz con velas y canciones. La Navidad (**jul**) y la Pascua (**påsk**) son fiestas familiares importantes. La \"fika\" (**fika**) —pausa para el café con algo dulce— es una costumbre social diaria. Valores como el \"lagom\" (ni mucho ni poco) y la igualdad marcan la vida cotidiana. La naturaleza y la vida al aire libre (**friluftsliv**) se valoran mucho.",
      palabras: [{"sv":"traditioner","es":"tradiciones"},{"sv":"midsommar","es":"solsticio de verano"},{"sv":"Lucia","es":"Santa Lucía"},{"sv":"jul","es":"Navidad"},{"sv":"fika","es":"pausa del café"},{"sv":"friluftsliv","es":"vida al aire libre"}],
      questions: [
        {"q":"Vad firar man på midsommar i Sverige?","qEs":"¿Qué se celebra en midsommar en Suecia?","options":["En kung","Vinterns kyla","Nyår","Sommarens ljusa dagar"],"correct":3,"exp":"En midsommar se celebran los días luminosos del verano.","phrase":"Rätt! På midsommar firar man sommaren.","why":"El midsommar (solsticio de verano) es una de las fiestas más queridas: se baila alrededor del \"majstång\" y se disfruta de la naturaleza."},
        {"q":"Vad är Lucia?","qEs":"¿Qué es Lucia?","options":["En sommarfest","En maträtt","En ljusfest i december","En sport"],"correct":2,"exp":"Lucia es una fiesta de la luz en diciembre.","phrase":"Rätt! Lucia är en ljusfest i december."},
        {"q":"Vad betyder \"fika\"?","qEs":"¿Qué significa \"fika\"?","options":["En lag","En religion","En sport","En kaffepaus med något gott"],"correct":3,"exp":"\"Fika\" es la pausa social para tomar café con algo dulce.","phrase":"Rätt! Fika är en kaffepaus.","why":"La fika es una costumbre diaria muy sueca: parar para tomar café o té con un bollo y socializar."},
        {"q":"Vad värdesätter många svenskar i vardagen?","qEs":"¿Qué valoran muchos suecos en el día a día?","options":["Bara arbete","Att inte gå ut","Natur och friluftsliv","Lyx"],"correct":2,"exp":"Muchos suecos valoran la naturaleza y la vida al aire libre.","phrase":"Rätt! Natur och friluftsliv är viktigt."},
        {"q":"Du blir bjuden på fika av en granne. Vad innebär det oftast?","qEs":"Un vecino te invita a \"fika\". ¿Qué significa normalmente?","options":["Ett förhör","Ett affärsmöte","En religiös ceremoni","Att umgås över kaffe och något gott"],"correct":3,"isCase":true,"exp":"Significa socializar tomando café con algo dulce.","phrase":"Rätt! Fika betyder att umgås över kaffe.","why":"Ser invitado a \"fika\" es un gesto amistoso y cotidiano para conversar y conocerse; es parte central de la cultura sueca."},
        {"q":"När firar man jul i Sverige?","qEs":"¿Cuándo se celebra la Navidad en Suecia?","options":["I juni","I december, julafton är den 24 december","I mars","I augusti"],"correct":1,"exp":"En diciembre; la Nochebuena (julafton) es el 24 de diciembre.","phrase":"Rätt! Julafton firas den 24 december."},
        {"q":"Vad är allemansrätten?","qEs":"¿Qué es el \"allemansrätten\" (derecho de acceso a la naturaleza)?","options":["Rätten att äga all mark","En skatt","Rätten att jaga fritt","Rätten att röra sig fritt i naturen med ansvar"],"correct":3,"exp":"Es el derecho a moverse libremente por la naturaleza, con responsabilidad.","phrase":"Rätt! Allemansrätten ger tillgång till naturen."},
        {"q":"Vad gör många svenskar på sommaren?","qEs":"¿Qué hacen muchos suecos en verano?","options":["Tar semester och njuter av naturen","Arbetar mer än vanligt","Firar jul","Går i skolan"],"correct":0,"exp":"Toman vacaciones y disfrutan de la naturaleza.","phrase":"Rätt! På sommaren tar många semester."},
        {"q":"Vad är typisk svensk mat?","qEs":"¿Cuál es la comida típica sueca?","options":["Bara pizza och tacos","Köttbullar, sill och knäckebröd","Bara hamburgare","Bara sushi"],"correct":1,"exp":"Albóndigas (köttbullar), arenque (sill) y pan crujiente (knäckebröd).","phrase":"Rätt! Köttbullar och sill är typiskt svenskt."},
        {"q":"Du är bjuden hem till en svensk familj. Vad är vanligt att göra vid dörren?","qEs":"Te invitan a casa de una familia sueca. ¿Qué es habitual hacer en la puerta?","options":["Ta av sig skorna inomhus","Ge pengar till värden","Ta med egen mat alltid","Ha kvar skorna på"],"correct":0,"isCase":true,"exp":"Quitarse los zapatos al entrar en casa.","phrase":"Rätt! Man tar av sig skorna inomhus.","why":"En Suecia es habitual y educado quitarse los zapatos al entrar en casa de alguien."}
      ]
    }
  ]
};

if (typeof window !== "undefined") window.MEDBORGAR = MEDBORGAR;
